includes:
- common/defaults/configs/datasets/vqa/crn_stvqa.yml
# Use soft copy
dataset_attributes:
  crn_stvqa:
    image_features:
      train:
      - m4c_stvqa_obj_frcn_features/train,m4c_stvqa_ocr_en_frcn_features/train,edge_feat
      val:
      - m4c_stvqa_obj_frcn_features/train,m4c_stvqa_ocr_en_frcn_features/train,edge_feat
      test:
      - m4c_stvqa_obj_frcn_features/test_task2,m4c_stvqa_ocr_en_frcn_features/test_task2,edge_feat
    imdb_files:
      train:
      - imdb/imdb_subtrain.npy
      val:
      - imdb/imdb_subval.npy
      test:
      - imdb/imdb_test_task2.npy
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          max_length: 20
      answer_processor:
        type: m4c_answer
        params:
          vocab_file: vocabs/answers_task2.txt
          preprocessor:
            type: simple_word
            params: {}
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 50
          max_copy_steps: 12
          num_answers: 10
      copy_processor:
        type: copy
        params:
          max_length: 100
      phoc_processor:
        type: phoc
        params:
          max_length: 50
model_attributes:
  crn:
    lr_scale_frcn: 0.1
    lr_scale_text_bert: 0.1
    lr_scale_mmt: 1.0  # no scaling
    text_bert_init_from_bert_base: true
    text_bert:
      num_hidden_layers: 3
    obj:
      mmt_in_dim: 2048
      dropout_prob: 0.1
    ocr:
      mmt_in_dim: 3002  # 300 (FastText) + 604 (PHOC) + 2048 (Faster R-CNN) + 50 (all zeros; legacy)
      dropout_prob: 0.1
    PAM:
      hidden_size: 768
      num_hidden_layers: 2
    MRG:
      hidden_size: 768
    mmt:
      hidden_size: 768
      num_hidden_layers: 4
    classifier:
      type: linear
      ocr_max_num: 50
      ocr_ptr_net:
        hidden_size: 768
        query_key_size: 768
      params: {}
    model_data_dir: ../data/crn_stvqa
    metrics:
    - type: stvqa_accuracy
    - type: stvqa_anls
    losses:
    - type: multi
      params:
      - type: m4c_decoding_bce_with_mask
        weight: 1.0
        params: {}
      - type: anls_reward
        weight: 1.0
        params: {}
optimizer_attributes:
  params:
    eps: 1.0e-08
    lr: 1e-4
    weight_decay: 0
  type: Adam
training_parameters:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    lr_steps:
    - 10000
    - 20000
    lr_ratio: 0.1
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 1000
    max_iterations: 25000
    batch_size: 146
    num_workers: 8
    task_size_proportional_sampling: true
    monitored_metric: crn_stvqa/stvqa_accuracy
    metric_minimize: false
